services:
  postgres:
    image: postgres:16
    container_name: cinetrack-db
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: cinetrack
      POSTGRES_PASSWORD: cinetrack
      POSTGRES_DB: cinetrack
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
